### PR TITLE
feat: ✨ V1 for RAG + AI Endpoints + LangChain + Python

### PR DESCRIPTION
**Pull request by philippart-s**
First version of a RAG example with AI Endpoints

### CODE REVIEW

**Comment by philippart-s** [comment]
@titimoby need your help 🙏, I'm not sure to understand all my code 😅

**Comment by titimoby** [comment]
maybe it's better to talk about it then do a review. What do you think?

**Comment by titimoby** [comment]
It looks good and is the way to go if we compare with what has been done in https://github.com/langchain-ai/langchain/tree/c1fced926923f7cf9bb982e3d0c610aa9dff6f35/libs/community/langchain_community/embeddings

I don't have all information for now, but it really looks like a potential contribution to community package.

**Comment by philippart-s** [comment]
> maybe it's better to talk about it then do a review. What do you think?

totally agree 🤩

**Comment by philippart-s** [comment]
⚠️ The code is not working until the LangChain community dependency is not released with the OVHcloud embedding model connector ⚠️

**Comment by philippart-s** [comment]
With the new version of langchain-community everything is working

**Pull request merged**
